#!/usr/bin/env python3
"""
image_scraper.py — Playwright-based image scraper for JavaScript-rendered sites (React, Vite, Next.js, etc.)
Author: generated by Claude
"""

import asyncio
import re
import sys
import hashlib
import mimetypes
from pathlib import Path
from urllib.parse import urljoin, urlparse

import httpx
from playwright.async_api import async_playwright
from rich.console import Console
from rich.progress import Progress, SpinnerColumn, BarColumn, TextColumn, TimeElapsedColumn
from rich.table import Table
from rich import print as rprint

console = Console()


# ─────────────────────────────────────────────
#  Helpers
# ─────────────────────────────────────────────

def slugify_url(url: str) -> str:
    """Turn a URL into a safe filename, preserving the original extension."""
    parsed = urlparse(url)
    name = Path(parsed.path).name or "image"
    # strip query strings from extension detection
    name_clean = name.split("?")[0]
    ext = Path(name_clean).suffix or ".jpg"
    digest = hashlib.md5(url.encode()).hexdigest()[:8]
    stem = re.sub(r"[^\w\-]", "_", Path(name_clean).stem)[:40]
    return f"{stem}_{digest}{ext}"


def guess_extension(content_type: str, url: str) -> str:
    """Return a file extension based on Content-Type or URL."""
    ct = content_type.split(";")[0].strip().lower()
    ext = mimetypes.guess_extension(ct)
    # mimetypes sometimes returns .jpe instead of .jpg
    mapping = {".jpe": ".jpg", ".jpeg": ".jpg", None: Path(urlparse(url).path).suffix or ".jpg"}
    return mapping.get(ext, ext)


def is_image_url(url: str) -> bool:
    """Heuristic: does this URL look like an image?"""
    IMAGE_EXTS = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".avif", ".ico", ".bmp", ".tiff"}
    IMAGE_PATTERNS = ["image/", "/assets/", "/images/", "/img/", "/media/", "/static/"]
    path = urlparse(url).path.lower()
    if any(path.endswith(ext) for ext in IMAGE_EXTS):
        return True
    if any(pat in url.lower() for pat in IMAGE_PATTERNS):
        return True
    return False


def resolve_url(base: str, src: str) -> str | None:
    """Resolve relative or protocol-relative URLs."""
    if not src or src.startswith("data:"):
        return None
    if src.startswith("//"):
        src = "https:" + src
    return urljoin(base, src)


# ─────────────────────────────────────────────
#  Playwright page crawl
# ─────────────────────────────────────────────

async def collect_image_urls(url: str, scroll: bool = True, timeout: int = 15000) -> set[str]:
    """
    Launch a headless browser, render the page, optionally scroll to trigger
    lazy-loaded images, then collect every image URL found via:
      • <img src / srcset>
      • <source srcset> (picture element)
      • background-image CSS
      • Network responses intercepted during load
    """
    found: set[str] = set()

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=True)
        context = await browser.new_context(
            viewport={"width": 1920, "height": 1080},
            user_agent=(
                "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                "AppleWebKit/537.36 (KHTML, like Gecko) "
                "Chrome/124.0.0.0 Safari/537.36"
            ),
        )
        page = await context.new_page()

        # --- Intercept network responses ---
        async def on_response(response):
            ct = response.headers.get("content-type", "")
            if "image" in ct:
                found.add(response.url)

        page.on("response", on_response)

        console.log(f"[cyan]Navigating to[/cyan] {url}")
        await page.goto(url, wait_until="networkidle", timeout=timeout)

        # --- Scroll to trigger lazy loading ---
        if scroll:
            console.log("[yellow]Scrolling page to trigger lazy-loaded images…[/yellow]")
            prev_height = 0
            for _ in range(15):
                await page.evaluate("window.scrollBy(0, window.innerHeight * 1.5)")
                await asyncio.sleep(0.6)
                height = await page.evaluate("document.body.scrollHeight")
                if height == prev_height:
                    break
                prev_height = height
            await page.evaluate("window.scrollTo(0, 0)")
            await asyncio.sleep(1)

        # --- DOM extraction ---
        console.log("[cyan]Extracting image URLs from DOM…[/cyan]")
        srcs: list[str] = await page.evaluate("""() => {
            const urls = new Set();

            // <img src>
            document.querySelectorAll('img[src]').forEach(el => urls.add(el.src));

            // <img srcset>
            document.querySelectorAll('img[srcset]').forEach(el => {
                el.srcset.split(',').forEach(part => {
                    const u = part.trim().split(/\\s+/)[0];
                    if (u) urls.add(new URL(u, location.href).href);
                });
            });

            // <source srcset> inside <picture>
            document.querySelectorAll('source[srcset]').forEach(el => {
                el.srcset.split(',').forEach(part => {
                    const u = part.trim().split(/\\s+/)[0];
                    if (u) urls.add(new URL(u, location.href).href);
                });
            });

            // CSS background-image (inline styles)
            document.querySelectorAll('*').forEach(el => {
                const bg = getComputedStyle(el).backgroundImage;
                const match = bg.match(/url\\(["']?([^"')]+)["']?\\)/);
                if (match) {
                    try { urls.add(new URL(match[1], location.href).href); } catch {}
                }
            });

            return [...urls];
        }""")

        for src in srcs:
            resolved = resolve_url(url, src)
            if resolved:
                found.add(resolved)

        await browser.close()

    # filter to image-like URLs only
    return {u for u in found if is_image_url(u)}


# ─────────────────────────────────────────────
#  Downloader
# ─────────────────────────────────────────────

async def download_images(
    image_urls: set[str],
    output_dir: Path,
    concurrency: int = 8,
) -> tuple[list[Path], list[tuple[str, str]]]:
    """Download all collected images concurrently."""
    output_dir.mkdir(parents=True, exist_ok=True)
    sem = asyncio.Semaphore(concurrency)
    downloaded: list[Path] = []
    failed: list[tuple[str, str]] = []

    async def fetch(client: httpx.AsyncClient, url: str, progress, task) -> None:
        async with sem:
            try:
                r = await client.get(url, follow_redirects=True, timeout=20)
                r.raise_for_status()
                ct = r.headers.get("content-type", "")
                ext = guess_extension(ct, url)
                filename = slugify_url(url)
                # ensure correct extension
                if not filename.lower().endswith(ext.lower()):
                    filename = Path(filename).stem + ext
                dest = output_dir / filename
                # avoid overwriting identical files
                counter = 1
                while dest.exists():
                    dest = output_dir / f"{Path(filename).stem}_{counter}{ext}"
                    counter += 1
                dest.write_bytes(r.content)
                downloaded.append(dest)
            except Exception as exc:
                failed.append((url, str(exc)))
            finally:
                progress.advance(task)

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TextColumn("{task.completed}/{task.total}"),
        TimeElapsedColumn(),
        console=console,
    ) as progress:
        task = progress.add_task("[green]Downloading images…", total=len(image_urls))
        async with httpx.AsyncClient(
            headers={"User-Agent": "Mozilla/5.0 image-scraper/1.0"},
            follow_redirects=True,
        ) as client:
            await asyncio.gather(*[fetch(client, u, progress, task) for u in image_urls])

    return downloaded, failed


# ─────────────────────────────────────────────
#  Report
# ─────────────────────────────────────────────

def print_report(downloaded: list[Path], failed: list[tuple[str, str]], output_dir: Path) -> None:
    console.rule("[bold green]Scraping Complete")
    table = Table(show_header=True, header_style="bold magenta")
    table.add_column("Metric", style="cyan", no_wrap=True)
    table.add_column("Value", style="white")
    table.add_row("✅ Downloaded", str(len(downloaded)))
    table.add_row("❌ Failed", str(len(failed)))
    table.add_row("📁 Output folder", str(output_dir.resolve()))
    total_bytes = sum(p.stat().st_size for p in downloaded if p.exists())
    table.add_row("💾 Total size", f"{total_bytes / 1024:.1f} KB" if total_bytes < 1_048_576 else f"{total_bytes / 1_048_576:.2f} MB")
    console.print(table)

    if failed:
        console.rule("[bold red]Failed URLs")
        for url, reason in failed[:20]:
            rprint(f"  [red]✗[/red] {url[:80]}…  →  [dim]{reason}[/dim]")
        if len(failed) > 20:
            console.print(f"  … and {len(failed) - 20} more.")


# ─────────────────────────────────────────────
#  CLI entry point
# ─────────────────────────────────────────────

async def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(
        description="🖼️  Download all images from a JavaScript-rendered website (React, Vite, Next.js, etc.)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python image_scraper.py https://example.com
  python image_scraper.py https://example.com -o ./downloads --no-scroll
  python image_scraper.py https://example.com -c 16 --timeout 30
        """,
    )
    parser.add_argument("url", help="Target URL to scrape")
    parser.add_argument("-o", "--output", default="./images", help="Output directory (default: ./images)")
    parser.add_argument("-c", "--concurrency", type=int, default=8, help="Parallel download workers (default: 8)")
    parser.add_argument("--no-scroll", action="store_true", help="Disable auto-scroll (faster, may miss lazy images)")
    parser.add_argument("--timeout", type=int, default=15, help="Page load timeout in seconds (default: 15)")
    parser.add_argument("--min-size", type=int, default=0, help="Skip images smaller than N bytes after download (default: 0)")
    args = parser.parse_args()

    output_dir = Path(args.output)
    console.rule(f"[bold blue]Image Scraper[/bold blue]")
    console.print(f"[bold]Target:[/bold] {args.url}")
    console.print(f"[bold]Output:[/bold] {output_dir.resolve()}\n")

    # Step 1 — collect
    image_urls = await collect_image_urls(
        args.url,
        scroll=not args.no_scroll,
        timeout=args.timeout * 1000,
    )
    console.print(f"\n[bold green]{len(image_urls)} image URL(s) found.[/bold green]\n")

    if not image_urls:
        console.print("[yellow]No images found. Try increasing --timeout or check if the site requires authentication.[/yellow]")
        sys.exit(0)

    # Step 2 — download
    downloaded, failed = await download_images(image_urls, output_dir, concurrency=args.concurrency)

    # Step 3 — optional size filter
    if args.min_size > 0:
        removed = [p for p in downloaded if p.exists() and p.stat().st_size < args.min_size]
        for p in removed:
            p.unlink()
        downloaded = [p for p in downloaded if p not in removed]
        if removed:
            console.print(f"[yellow]Removed {len(removed)} image(s) smaller than {args.min_size} bytes.[/yellow]")

    print_report(downloaded, failed, output_dir)


if __name__ == "__main__":
    asyncio.run(main())